import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { ThemeProvider } from '@/context/theme/ThemeProvider';
import './globals.css';
import { Navbar } from '@/components/Navbar';
import prisma from '@/lib/db';
import { getKindeServerSession } from '@kinde-oss/kinde-auth-nextjs/server';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const fetchUserData = async (userId: string) => {
  if (userId) {
    const userData = await prisma.user.findUnique({
      where: {
        id: userId,
      },
      select: {
        colorTheme: true,
      },
    });

    return userData;
  }
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { getUser } = await getKindeServerSession();

  const user = await getUser();

  const userData = await fetchUserData(user?.id!);

  return (
    <html lang='en' suppressHydrationWarning>
      <body
        className={`${inter.className} ${
          userData?.colorTheme || 'theme-purple'
        } flex flex-col h-screen`}
      >
        <ThemeProvider
          attribute='class'
          defaultTheme='dark'
          enableSystem
          disableTransitionOnChange
        >
          <Navbar />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
